version: "3.7"
services:
  client:
    build:
      context: frontend
    restart: unless-stopped
    ports:
      - "4000:3000"

  backend:
    build: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail http://localhost:5000/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
