FROM python:3.8-slim-buster
WORKDIR /usr/src/app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
# CMD [ "gunicorn", "main:app", "--bind", "0.0.0.0:5000" ]
CMD [ "python3", "main.py" ]